@ Auto-generated by peel.py wiring — raw bytes section
@ Range:  [0x80313fc, 0x080315d8)  (476 bytes)

        .include "asm/macros.inc"
        .syntax unified

        .text
        .align 2

        .global text_0x08031390_after
text_0x08031390_after:
        .incbin "baserom.gba", 0x313fc, 0x1dc
