@ Auto-generated by peel.py wiring — raw bytes section
@ Range:  [0x08031540, 0x080315d8)  (152 bytes)

        .include "asm/macros.inc"
        .syntax unified

        .text
        .align 2

        .global text_0x08031390_after
text_0x08031390_after:
        .incbin "baserom.gba", 0x31540, 0x98
